### ISSUE TITLE
Getting error, to up and running

### ISSUE THREAD

**Issue by jitendra3109** [nitin42/redocx#4]
> babel-node ./demo/Word.js

/usr/bin/env: ‘node’: No such file or directory

npm ERR! Linux 4.10.0-32-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "example"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! redocx@1.0.1 example: `babel-node ./demo/Word.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the redocx@1.0.1 example script 'babel-node ./demo/Word.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the redocx package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node ./demo/Word.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs redocx
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls redocx
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jsroyal/redocx/npm-debug.log

I could not get it.

**Comment by nitin42** [comment]
Oh! This error is not caused due to redocx, read here - https://github.com/nodejs/node-v0.x-archive/issues/3911
