### ISSUE TITLE
no online demo

### ISSUE THREAD

**Issue by bardiarastin** [nitin42/redocx#5]
is it possible to provide some online demo ?

**Comment by nitin42** [comment]
Sure! I was already thinking about it but I've been busy with the cli and some other bugs. I'll try to make web demo.

**Comment by nitin42** [comment]
umm.. I've created an issue for `officegen` to support browser build because currently we cannot use `officegen` in browser even if we transpile the `require()` calls.

**Comment by bardiarastin** [comment]
it already has an open issue for browser support 
https://github.com/Ziv-Barber/officegen/issues/126

**Comment by nitin42** [comment]
I didn't noticed. Thanks!

**Comment by pimlottc-gov** [comment]
At the very least, it would be nice to have sample Word docs produced by this tool available so people can see what the output looks like.

**Comment by nitin42** [comment]
Sure! I'll try to wrap up a demo next week.
